version: "3.8"

services:
        weather:
                image: mannx/weather
                container_name: weather
                ports:
                        - 8080:8080
                deploy:
                        restart_policy:
                                condition: on-failure
